import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { Navbar } from '@/components/Navbar';
import { Box } from '@chakra-ui/react';
import {
  HomePageHero,
  HomePageScreenshots,
  HomePageCommitments,
  HomePageTasks,
  HomePageDownload,
} from '@/components';

export default function Home() {
  return (
    <>
      <Head>
        <title>TimeToGive</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg="gray.800" position="relative">
        <header>
          <Navbar />
        </header>
        <main>
          <HomePageHero />
          <HomePageScreenshots />
          <HomePageTasks />
          <HomePageCommitments />
          <HomePageDownload />
        </main>
      </Box>
    </>
  );
}
